import scrapy


class TournamentItem(scrapy.Item):
    tournament_name = scrapy.Field()

    tournament_category_name = scrapy.Field()
    tournament_category_id = scrapy.Field()

    tournament_unique_name = scrapy.Field()
    tournament_has_statistics = scrapy.Field()

    tournament_session_name = scrapy.Field()
    tournament_session_year = scrapy.Field()
    tournament_session_id = scrapy.Field()

    tournament_round = scrapy.Field()
    tournament_round_name = scrapy.Field()

    tournament_status_code = scrapy.Field()
    tournament_status_description = scrapy.Field()

    tournament_winner_code = scrapy.Field()

    tournament_home_team_name = scrapy.Field()
    tournament_home_team_country = scrapy.Field()
    tournament_home_team_id = scrapy.Field()
    tournament_home_team_color_primary = scrapy.Field()
    tournament_home_team_color_secondary = scrapy.Field()

    tournament_away_team_name = scrapy.Field()
    tournament_away_team_country = scrapy.Field()
    tournament_away_team_id = scrapy.Field()
    tournament_away_team_color_primary = scrapy.Field()
    tournament_away_team_color_secondary = scrapy.Field()

    tournament_home_score = scrapy.Field()
    tournament_home_score_period_1 = scrapy.Field()
    tournament_home_score_period_2 = scrapy.Field()
    tournament_home_score_overtime = scrapy.Field()
    tournament_home_score_extra1 = scrapy.Field()
    tournament_home_score_extra2 = scrapy.Field()

    tournament_away_score = scrapy.Field()
    tournament_away_score_period_1 = scrapy.Field()
    tournament_away_score_period_2 = scrapy.Field()
    tournament_away_score_overtime = scrapy.Field()
    tournament_away_score_extra1 = scrapy.Field()
    tournament_away_score_extra2 = scrapy.Field()

    tournament_time_1 = scrapy.Field()
    tournament_time_2 = scrapy.Field()
    tournament_time_3 = scrapy.Field()
    tournament_time_4 = scrapy.Field()

    tournament_has_global_highlights = scrapy.Field()
    tournament_id = scrapy.Field()
    tournament_start_timestamp = scrapy.Field()


class StatisticItem(scrapy.Item):
    url = scrapy.Field()
    tournament_id = scrapy.Field()

    statistic_period = scrapy.Field()
    statistic_group_name = scrapy.Field()
    statistic_name = scrapy.Field()
    statistic_type = scrapy.Field()
    statistic_home_value = scrapy.Field()
    statistic_away_value = scrapy.Field()
    statistic_compare_code = scrapy.Field()


class LineupItem(scrapy.Item):
    lineup_confirmed = scrapy.Field()
    home_id_ = scrapy.Field()
    home_name = scrapy.Field()
    home_short_name = scrapy.Field()
    home_date_of_birth = scrapy.Field()
    home_country = scrapy.Field()
    home_user_count = scrapy.Field()
    home_shirt_number = scrapy.Field()
    home_position = scrapy.Field()
    home_substitute = scrapy.Field()
    home_statistics = scrapy.Field()
    home_total_pass = scrapy.Field()
    home_accurate_pass = scrapy.Field()
    home_total_long_balls = scrapy.Field()
    home_accurate_long_balls = scrapy.Field()
    home_aerial_lost = scrapy.Field()
    home_aerial_won = scrapy.Field()
    home_duel_lost = scrapy.Field()
    home_duel_won = scrapy.Field()
    home_challenge_lost = scrapy.Field()
    home_total_contest = scrapy.Field()
    home_won_contest = scrapy.Field()
    home_interception_won = scrapy.Field()
    home_was_fouled = scrapy.Field()
    home_total_tackle = scrapy.Field()
    home_fouls = scrapy.Field()
    home_minutes_played = scrapy.Field()
    home_touches = scrapy.Field()
    home_rating = scrapy.Field()
    home_possession_lost_ctrl = scrapy.Field()
    home_rating_version = scrapy.Field()
    home_good_high_claim = scrapy.Field()
    home_saves = scrapy.Field()
    home_goals_prevented = scrapy.Field()
    home_total_cross = scrapy.Field()
    home_accurate_cross = scrapy.Field()
    home_duel_lost = scrapy.Field()
    home_duel_won = scrapy.Field()
    home_challenge_lost = scrapy.Field()
    home_total_contest = scrapy.Field()
    home_won_contest = scrapy.Field()
    home_big_chance_missed = scrapy.Field()
    home_short_of_target = scrapy.Field()
    home_blocked_scoring_attempt = scrapy.Field()
    home_hit_woodwork = scrapy.Field()
    home_total_clearance = scrapy.Field()
    home_total_tackle = scrapy.Field()
    home_was_fouled = scrapy.Field()
    home_saved_shots_from_inside_the_box = scrapy.Field()
    home_saves = scrapy.Field()
    home_total_keeper_sweeper = scrapy.Field()
    home_accurate_keeper_sweeper = scrapy.Field()
    home_minutes_played = scrapy.Field()
    home_touches = scrapy.Field()
    home_expected_goals = scrapy.Field()
    home_key_passes = scrapy.Field()
    home_rating_version = scrapy.Field()
    home_rating = scrapy.Field()
    home_possession_lost_ctrl = scrapy.Field()
    home_goals_prevented = scrapy.Field()
    home_expected_assists = scrapy.Field()

    away_id_ = scrapy.Field()
    away_name = scrapy.Field()
    away_short_name = scrapy.Field()
    away_date_of_birth = scrapy.Field()
    away_country = scrapy.Field()
    away_user_count = scrapy.Field()
    away_shirt_number = scrapy.Field()
    away_position = scrapy.Field()
    away_substitute = scrapy.Field()
    away_statistics = scrapy.Field()
    away_total_pass = scrapy.Field()
    away_accurate_pass = scrapy.Field()
    away_total_long_balls = scrapy.Field()
    away_accurate_long_balls = scrapy.Field()
    away_aerial_lost = scrapy.Field()
    away_aerial_won = scrapy.Field()
    away_duel_lost = scrapy.Field()
    away_duel_won = scrapy.Field()
    away_challenge_lost = scrapy.Field()
    away_total_contest = scrapy.Field()
    away_won_contest = scrapy.Field()
    away_interception_won = scrapy.Field()
    away_was_fouled = scrapy.Field()
    away_total_tackle = scrapy.Field()
    away_fouls = scrapy.Field()
    away_minutes_played = scrapy.Field()
    away_touches = scrapy.Field()
    away_rating = scrapy.Field()
    away_possession_lost_ctrl = scrapy.Field()
    away_rating_version = scrapy.Field()
    away_good_high_claim = scrapy.Field()
    away_saves = scrapy.Field()
    away_goals_prevented = scrapy.Field()
    away_total_cross = scrapy.Field()
    away_accurate_cross = scrapy.Field()
    away_duel_lost = scrapy.Field()
    away_duel_won = scrapy.Field()
    away_challenge_lost = scrapy.Field()
    away_total_contest = scrapy.Field()
    away_won_contest = scrapy.Field()
    away_big_chance_missed = scrapy.Field()
    away_short_of_target = scrapy.Field()
    away_blocked_scoring_attempt = scrapy.Field()
    away_hit_woodwork = scrapy.Field()
    away_total_clearance = scrapy.Field()
    away_total_tackle = scrapy.Field()
    away_was_fouled = scrapy.Field()
    away_saved_shots_from_inside_the_box = scrapy.Field()
    away_saves = scrapy.Field()
    away_total_keeper_sweeper = scrapy.Field()
    away_accurate_keeper_sweeper = scrapy.Field()
    away_minutes_played = scrapy.Field()
    away_touches = scrapy.Field()
    away_expected_goals = scrapy.Field()
    away_key_passes = scrapy.Field()
    away_rating_version = scrapy.Field()
    away_rating = scrapy.Field()
    away_possession_lost_ctrl = scrapy.Field()
    away_goals_prevented = scrapy.Field()
    away_expected_assists = scrapy.Field()
